[build]
  base      = "dividendiq"
  functions = "netlify/functions"
  publish   = "public"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
